global:
  # Slack API URL - Replace with your actual Slack webhook URL
  slack_api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'

templates:
  - '/etc/alertmanager/templates.tmpl'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'slack-critical'
  - match:
      severity: warning
    receiver: 'slack-warning'

receivers:
- name: 'web.hook'
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'
    channel: '#alerts'
    title: 'Notrus Alert'
    text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ "\n" }}{{ .Annotations.description }}{{ end }}'

- name: 'slack-critical'
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'
    channel: '#critical-alerts'
    username: 'Notrus Alert Manager'
    icon_emoji: ':rotating_light:'
    title: '{{ template "slack.notrus.title" . }}'
    color: '{{ template "slack.notrus.color" . }}'
    text: '{{ template "slack.notrus.text" . }}'
    actions:
    - type: button
      text: 'View in Prometheus'
      url: 'http://localhost:9090/alerts'
    - type: button
      text: 'View in Grafana'
      url: 'http://localhost:3001'
    send_resolved: true

- name: 'slack-warning'
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL_HERE'
    channel: '#warnings'
    username: 'Notrus Alert Manager'
    icon_emoji: ':warning:'
    title: '{{ template "slack.notrus.title" . }}'
    color: '{{ template "slack.notrus.color" . }}'
    text: '{{ template "slack.notrus.text" . }}'
    actions:
    - type: button
      text: 'View in Prometheus'
      url: 'http://localhost:9090/alerts'
    - type: button
      text: 'View in Grafana'
      url: 'http://localhost:3001'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']